import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('🏠 ROOT LAYOUT: Rendering layout with children');
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased text-slate-900 dark:text-slate-100`}
      >
        {/* Pure black background */}
        <div className="fixed inset-0 -z-50 bg-black" />
        
        {/* Fine noise over everything (prevents plastic look) */}
        <div
          className="pointer-events-none fixed inset-0 -z-30 mix-blend-overlay"
          style={{ 
            backgroundImage: 'var(--noise)', 
            opacity: 'var(--noise-opacity)' 
          }}
        />
        
        {/* Removed inline script for better hygiene */}
        {children}
      </body>
    </html>
  );
}
