import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased text-slate-900 dark:text-slate-100`}
      >
        {/* Base gradient */}
        <div className="fixed inset-0 -z-50 bg-gradient-to-br from-white via-sky-50 to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950" />
        
        {/* Accent radial "bloom" */}
        <div className="fixed inset-0 -z-40 bg-accent-radial dark:bg-accent-radial-dark" />
        
        {/* Fine noise over everything (prevents plastic look) */}
        <div
          className="pointer-events-none fixed inset-0 -z-30 mix-blend-overlay"
          style={{ 
            backgroundImage: 'var(--noise)', 
            opacity: 'var(--noise-opacity)' 
          }}
        />
        
        {children}
      </body>
    </html>
  );
}
